#!/bin/bash
set -e

operation=$1
shift

if ! [ -x "$(command -v jq)" ]; then
    echo "Install https://stedolan.github.io/jq"
    exit 1
fi

DOCKER_REGISTRY=`jq -r '.dockerRegistry' < local.json`
ACCESS_TOKEN=`jq -r '.witAccessToken' < local.json`

echo "Registry at : $DOCKER_REGISTRY"

docker_build() {
  docker build  -t speech-api .
}

docker_tag() {
   docker tag speech-api $DOCKER_REGISTRY
}

docker_push() {
  echo "Pushing to $DOCKER_REGISTRY"
  docker push $DOCKER_REGISTRY
}

docker_run() {
  WIT_ACCESS_TOKEN=$ACCESS_TOKEN docker run -it -e WIT_ACCESS_TOKEN -p 3000:3000 --rm --name speech-api-1 speech-api
}

case "$operation" in
  push)
    docker_build
    docker_tag
    docker_push
    ;;

  run)
    docker_build
    docker_run
    ;;

  *)
    echo "Invalid operation: $operation"
    exit 1
    ;;
esac
