#!/bin/bash
set -e

operation=$1
shift

DOCKER_REGISTRY=tutum.co/hirschfeld/speech

docker_build() {
  docker build  -t speech-api .
}

docker_tag() {
   docker tag speech-api $DOCKER_REGISTRY
}

docker_push() {
  docker push $DOCKER_REGISTRY
}

docker_run() {
  docker run -it -e WIT_ACCESS_TOKEN -p 3000:3000 --rm --name speech-api-1 speech-api
}

case "$operation" in
  push)
    docker_build
    docker_tag
    docker_push
    ;;

  run)
    docker_build
    docker_run
    ;;

  *)
    echo "Invalid operation: $operation"
    exit 1
    ;;
esac
